name: garda_green
description: The Garda Green game
version: 1.0.1+2
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: 3.19.0

dependencies:
  audioplayers: ^5.2.1
  bloc: ^8.1.3
  cloud_firestore: ^4.15.6
  equatable: ^2.0.5
  firebase_analytics: ^10.8.7
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  firebase_crashlytics: ^3.4.16
  flame: ^1.16.0
  flame_audio: ^2.10.0
  flame_behaviors: ^1.1.0
  flame_tiled: ^1.19.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  json_annotation: ^4.8.1
  nes_ui: ^0.17.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  flame_test: ^1.16.0
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  logger: ^2.0.2+1
  mockingjay: ^0.5.0
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/
    - assets/tiles/
    - assets/trivia/
    - assets/licenses/press_start_2p/
    - assets/waste/

  fonts:
    - family: Press Start 2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf

flutter_launcher_icons:
  android: true
  adaptive_icon_foreground: "./icon.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 26
  image_path: './icon.png'
  ios: 'icon.png'
  remove_alpha_ios: true
  web:
    generate: true
    image_path: 'icon.png'
    background_color: '#0175C2'
    theme_color: '#0175C2'
  windows:
    generate: true
    image_path: 'icon.png'
    icon_size: 48
  macos:
    generate: true
    image_path: 'icon.png'
