name: garda_green
description: The Garda Green game
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: 3.16.0

dependencies:
  audioplayers: ^5.2.0
  bloc: ^8.1.2
  equatable: ^2.0.5
  cloud_firestore: ^4.15.4
  firebase_analytics: ^10.8.5
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  flame: ^1.10.1
  flame_audio: ^2.1.3
  flame_behaviors: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.0.0
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.5
  flame_test: ^1.14.0
  flutter_test:
    sdk: flutter
  mockingjay: ^0.5.0
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/licenses/poppins/
