name: garda_green
description: The Garda Green game
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: 3.16.0

dependencies:
  audioplayers: ^5.2.1
  bloc: ^8.1.2
  equatable: ^2.0.5
  cloud_firestore: ^4.15.4
  firebase_analytics: ^10.8.5
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  flame: ^1.15.0
  flame_audio: ^2.1.8
  flame_behaviors: ^1.1.0
  flame_tiled: ^1.18.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  nes_ui: ^0.15.0
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.8
  flame_test: ^1.15.4
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  logger: ^2.0.2+1
  mockingjay: ^0.5.0
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/
    - assets/tiles/
    - assets/licenses/press_start_2p/

  fonts:
    - family: Press Start 2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
