// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjTYz8996jZOOOzBjfrZlKT6mBVGuIkuE',
    appId: '1:60399823875:web:c903b770edae89b865f236',
    messagingSenderId: '60399823875',
    projectId: 'garda-green',
    authDomain: 'garda-green.firebaseapp.com',
    storageBucket: 'garda-green.appspot.com',
    measurementId: 'G-CH31FDHV5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5tEViH7eCAxzmkCBgSGva3FtRnRLj0u4',
    appId: '1:60399823875:android:21ef479d965e876865f236',
    messagingSenderId: '60399823875',
    projectId: 'garda-green',
    storageBucket: 'garda-green.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqeHmf-aqGIAF-sj5bXmbggvs8lAwmOY8',
    appId: '1:60399823875:ios:9f2f2804031d7c4965f236',
    messagingSenderId: '60399823875',
    projectId: 'garda-green',
    storageBucket: 'garda-green.appspot.com',
    iosBundleId: 'me.hib4.gardaGreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqeHmf-aqGIAF-sj5bXmbggvs8lAwmOY8',
    appId: '1:60399823875:ios:e0c0dbf5f818de9c65f236',
    messagingSenderId: '60399823875',
    projectId: 'garda-green',
    storageBucket: 'garda-green.appspot.com',
    iosBundleId: 'me.hib4.gardaGreen.RunnerTests',
  );
}
