// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_development.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqAJGUylUj9HfUP7EU0GnQjCnLdx39UtI',
    appId: '1:837898680413:web:25e21b2dc04362d0f6f5b4',
    messagingSenderId: '837898680413',
    projectId: 'garda-green-development',
    authDomain: 'garda-green-development.firebaseapp.com',
    storageBucket: 'garda-green-development.appspot.com',
    measurementId: 'G-MMSV7E8B2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfqd1tGWHIm1Z_Iqjf_1KcSPW5dGzZ_m4',
    appId: '1:837898680413:android:aa2bcee1798d2089f6f5b4',
    messagingSenderId: '837898680413',
    projectId: 'garda-green-development',
    storageBucket: 'garda-green-development.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5cPatdU92-0aBl9n85HM8EusrPvrGAtU',
    appId: '1:837898680413:ios:1ac9bf7b663037d8f6f5b4',
    messagingSenderId: '837898680413',
    projectId: 'garda-green-development',
    storageBucket: 'garda-green-development.appspot.com',
    iosBundleId: 'me.hib4.gardaGreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5cPatdU92-0aBl9n85HM8EusrPvrGAtU',
    appId: '1:837898680413:ios:7ba7585f0bf273eaf6f5b4',
    messagingSenderId: '837898680413',
    projectId: 'garda-green-development',
    storageBucket: 'garda-green-development.appspot.com',
    iosBundleId: 'me.hib4.gardaGreen.RunnerTests',
  );
}
